# Generated by Django 6.0.4 on 2026-04-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('INVESTMENT', 'Investimento')], default='CHECKING', max_length=20, verbose_name='Tipo de Conta')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo atual')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('is_active', models.BooleanField(default=True, verbose_name='ContaAtiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.userprofile', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite de Crédito')),
                ('used_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Limite Utilizado')),
                ('closing_day', models.IntegerField(max_length=2, verbose_name='Dia de Fechamento')),
                ('due_day', models.IntegerField(max_length=2, verbose_name='Dia de Vencimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cartão Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='finance.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
