# Generated by Django 6.0.4 on 2026-04-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_card_closing_day_alter_card_due_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Conta Ativa'),
        ),
    ]
